name: monarch_mart # using Flutter 2.10.3 && Dart 2.16.1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.3+13

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.11
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  http: ^0.13.4
  expandable: ^5.0.1
  flutter_html: ^2.1.5
  font_awesome_flutter: ^9.2.0
  flutter_countdown_timer: ^4.1.0
  firebase_crashlytics: ^2.4.5
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.19
  firebase_messaging: ^11.2.5
  cloud_firestore: ^3.1.17
  dropdown_search: ^2.0.1
  timeline_tile: ^2.0.0
  permission_handler: ^8.3.0
  image_picker: ^0.8.4+4
  flutter_rating_bar: ^4.0.0
  flutter_local_notifications: ^9.2.0
  flutter_staggered_grid_view: ^0.6.1
  social_share: ^2.2.1
  intl: ^0.17.0
  flutter_screenutil: ^5.3.1
  google_fonts: ^2.3.1
  package_info_plus: ^1.4.0
  in_app_update: ^3.0.0
  fluttertoast: ^6.0.0
  upgrader: ^3.13.0
  webview_flutter:
  pin_code_fields: ^7.4.0
  get: ^4.6.5
  new_version: ^0.3.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - resources/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: resources/font/Poppins-Thin.ttf
          weight: 100
          style: normal
        - asset: resources/font/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        
        - asset: resources/font/Poppins-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: resources/font/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: resources/font/Poppins-Light.ttf
          weight: 300
          style: normal
        - asset: resources/font/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        - asset: resources/font/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: resources/font/Poppins-Italic.ttf
          weight: 400
          style: italic

        - asset: resources/font/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: resources/font/Poppins-MediumItalic.ttf
          weight: 500
          style: italic


        - asset: resources/font/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: resources/font/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        

        - asset: resources/font/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: resources/font/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: resources/font/Poppins-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: resources/font/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: resources/font/Poppins-Black.ttf
          weight: 900
          style: normal
        - asset: resources/font/Poppins-BlackItalic.ttf
          weight: 900
          style: italic